#!/usr/bin/env bash
# Install nginx web server
sudo apt-get -y update
sudo apt-get -y install nginx
sudo service nginx start
sudo bash -c 'echo "server {
    listen 80;
    server_name localhost;

    location / {
        echo \"Hello World!\";
        root /var/www/html;
        index index.html;
    }
}" > /etc/nginx/sites-available/default'
sudo service nginx restart
