#!/usr/bin/env bash
# Script that displays numbers from 1 to 100 FizzBuzz.
i=1
while (( i <= 100 )); do
    if (( i % 3 == 0 && i % 5 == 0 )); then
        echo "FizzBuzz"
    else
        if (( i % 3 == 0)); then
            echo "Fizz"
        elif (( i % 5 == 0)); then
            echo "Buzz"
        else
            echo $i
        fi
    fi
    i=$((i+1))
done