#!/usr/bin/env bash
# Script that displays the content of the file /etc/passwd.
path="/etc/passwd"
if [ -e $path ]; then
    exec 3< $path
    while IFS=':' read -r username _ uid _ _ homedir _; do
        echo "$username:$uid:$homedir"
    done <&3
fi
