#!/usr/bin/env bash
# Configures an Ubuntu server for localhost and facebook.com
HOSTFILE="/etc/hosts"
HOSTFILE_COPY="$HOME/hosts.new"
cp "$HOSTFILE" "$HOSTFILE_COPY"
sed -i "s/.*localhost$/127.0.0.2\tlocalhost/" "$HOSTFILE_COPY"
sed -i "s/.*facebook\.com$/8.8.8.8\tfacebook\.com/" "$HOSTFILE_COPY"
cp "$HOSTFILE_COPY" "$HOSTFILE"
